"$schema" =   'https://starship.rs/config.schema.json'

add_newline = true

command_timeout = 3600000

scan_timeout = 500

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_visual_symbol = "[❮](bold yellow)"

[package]
disabled = true

[nodejs]
symbol = " "
