github.com:
    user: brantty
    oauth_token: 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
    git_protocol: ssh
    users:
        brantty:
            oauth_token: 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
