local u = require("utils")
local c = u.create_cmd
local cmd, api, fn, d = vim.cmd, vim.api, vim.fn, vim.diagnostic

c("ToggleTermFish", function()
  u.toggle_term_cmd({ count = 4, cmd = "fish" })
end)
c("ToggleTermLazyDocker", function()
  u.toggle_term_cmd({ count = 2, cmd = "lazydocker" })
end)
c("ToggleTermLazyGit", function()
  u.toggle_term_cmd({ count = 3, cmd = "lazygit" })
end)
c("ToggleTermWeeChat", function()
  u.toggle_term_cmd({ count = 5, cmd = "weechat" })
end)
c("ToggleTermPowershell", function()
  u.toggle_term_cmd({ count = 10, cmd = "pwsh" })
end)
c("ToggleTermRepl", function()
  u.toggle_term_cmd({ count = 8, cmd = { "node", "lua", "irb", "fish", "bash", "python" } })
end)
c("ToggleTermSpotify", function()
  u.toggle_term_cmd({ count = 1, cmd = "spotify_player" })
end)
c("TerminalSendCmd", function()
  u.terminal_send_cmd("ls")
end)
c("TermOpenTab", function()
  u.term_open("tab term")
end)
c("TermOpenBottom", function()
  u.term_open("botright term")
end)
c("TermOpenBottomResized", function()
  u.term_open({
    "botright term",
    "botright resize 15%",
  })
end)
c("TermOpenBottomVert", function()
  u.term_open("horizontal term")
end)
c("TermOpenRight", function()
  u.term_open("vertical term")
end)
c("TermOpenRightResized", function()
  u.term_open({
    "vertical term",
    "vertical resize 50%",
  })
end)
